title: Conference Deadlines
description: Countdowns to conference deadlines that are interesting for SNL lab
author: SNL

domain: "to-do"
baseurl: ""

github_username: SNL-UCSB
github_repo: conf-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
