title: Conference Deadlines
description: Countdowns to conference deadlines that are interesting for SNL lab
author: SNL

domain: "https://snl-ucsb.github.io/conf-deadlines/"
baseurl: "https://snl-ucsb.github.io/conf-deadlines/"

github_username: SNL-UCSB
github_repo: conf-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
